INSERT INTO load
  ( sParentLoad, sLoadID, sWareHouse, sAddress, sDeviceID, sContainerType,
    sLoadMessage )
  SELECT 
    CONCAT (SUBSTR(lc.sAddress, 1, 6), SUBSTR(lc.sAddress, 8, 9)),
    CONCAT (SUBSTR(lc.sAddress, 1, 6), SUBSTR(lc.sAddress, 8, 9)),
    lc.sWarehouse, lc.sAddress, lc.sDeviceID, 'Tray',
    'AutoGeneratedDemoCenter'
  FROM Location lc
  WHERE lc.sWarehouse = 'AS1' AND lc.iLocationType = 10 AND lc.iEmptyFlag = 21;

UPDATE location SET location.iEmptyflag =  22
    WHERE location.iEmptyFlag = 21 AND (location.iLocationtype = 10)
    AND EXISTS 
       (SELECT sloadid FROM load WHERE load.sWarehouse = location.sWarehouse AND
        load.sAddress = location.sAddress);
