USE [EBSWRXJ]
GO
CREATE LOGIN [ronly] WITH PASSWORD='ronly', DEFAULT_DATABASE=[EBSWRXJ], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
CREATE USER ronly FROM LOGIN ronly;
GO
GRANT SELECT ON asrs.SYSTEMHB TO ronly;
GO
GRANT SELECT ON asrs.LOADLINEITEM TO ronly;
GO
GRANT SELECT ON asrs.LOAD TO ronly;
GO
GRANT SELECT ON asrs.LOCATION TO ronly;
GO
GRANT SELECT ON dbo.VIEW_HEARTBEAT TO ronly;
GO
GRANT SELECT ON dbo.VIEW_INVENTORY TO ronly;
GO
GRANT SELECT ON dbo.VIEW_LOCATION_STATUS TO ronly;
GO