use [EBSWRXJ];
GO

PRINT 'Deleting LOGIN Data'
DROP TABLE asrs.LOGIN;

PRINT 'Deleting EMPLOYEE Data'
DROP TABLE asrs.EMPLOYEE;

PRINT 'Deleting LOADLINEITEM Data'
DROP TABLE asrs.LOADLINEITEM;

PRINT 'Deleting LOAD Data'
DROP TABLE asrs.LOAD;

PRINT 'Deleting DEDICATEDLOCATION Data'
DROP TABLE asrs.DEDICATEDLOCATION;

PRINT 'Deleting ORDERLINE Data'
DROP TABLE asrs.ORDERLINE;

PRINT 'Deleting ORDERHEADER Data'
DROP TABLE asrs.ORDERHEADER;

PRINT 'Deleting PURCHASEORDERLINE Data'
DROP TABLE asrs.PURCHASEORDERLINE;

PRINT 'Deleting ROLEOPTION Data'
DROP TABLE asrs.ROLEOPTION;

PRINT 'Deleting SYNONYMS Data'
DROP TABLE asrs.SYNONYMS;

PRINT 'Deleting LOCATION Data'
DROP TABLE asrs.LOCATION;

PRINT 'Deleting DEVICE Data'
DROP TABLE asrs.DEVICE;

PRINT 'Deleting VEHICLEMOVE Data'
DROP TABLE asrs.VEHICLEMOVE;

PRINT 'Deleting VEHICLESYSTEMCMD Data'
DROP TABLE asrs.VEHICLESYSTEMCMD;

PRINT 'Deleting ASRSMETADATA Data'
DROP TABLE asrs.ASRSMETADATA;

PRINT 'Deleting CARRIER Data'
DROP TABLE asrs.CARRIER;

PRINT 'Deleting CONTAINERTYPE Data'
DROP TABLE asrs.CONTAINERTYPE;

PRINT 'Deleting CONTROLLERCONFIG Data'
DROP TABLE asrs.CONTROLLERCONFIG;

PRINT 'Deleting CUSTOMER Data'
DROP TABLE asrs.CUSTOMER;

PRINT 'Deleting TRANSACTIONHISTORY Data'
DROP TABLE asrs.TRANSACTIONHISTORY;

PRINT 'Deleting JVMCONFIG Data'
DROP TABLE asrs.JVMCONFIG;

PRINT 'Deleting HOSTTOWRX Data'
DROP TABLE asrs.HOSTTOWRX;

PRINT 'Deleting HOSTCONFIG Data'
DROP TABLE asrs.HOSTCONFIG;

PRINT 'Deleting HOSTOUTACCESS Data'
DROP TABLE asrs.HOSTOUTACCESS;

PRINT 'Deleting ITEMMASTER Data'
DROP TABLE asrs.ITEMMASTER;

PRINT 'Deleting LOADWORD Data'
DROP TABLE asrs.LOADWORD;

PRINT 'Deleting MOVE Data'
DROP TABLE asrs.MOVE;

PRINT 'Deleting PORT Data'
DROP TABLE asrs.PORT;

PRINT 'Deleting PURCHASEORDERHEADER Data'
DROP TABLE asrs.PURCHASEORDERHEADER;

PRINT 'Deleting REASONCODE Data'
DROP TABLE asrs.REASONCODE;

PRINT 'Deleting ROLE Data'
DROP TABLE asrs.ROLE;

PRINT 'Deleting ROUTE Data'
DROP TABLE asrs.ROUTE;

PRINT 'Deleting STATION Data'
DROP TABLE asrs.STATION;

PRINT 'Deleting SYSCONFIG Data'
DROP TABLE asrs.SYSCONFIG;

PRINT 'Deleting WAREHOUSE Data'
DROP TABLE asrs.WAREHOUSE;

PRINT 'Deleting WRXSEQUENCER Data'
DROP TABLE asrs.WRXSEQUENCER;

PRINT 'Deleting WRXTOHOST Data'
DROP TABLE asrs.WRXTOHOST;

PRINT 'Deleting ZONE Data'
DROP TABLE asrs.ZONE;

PRINT 'Deleting ZONEGROUP Data'
DROP TABLE asrs.ZONEGROUP;

PRINT 'Deleting EQUIPMENTMONITORSTATUS Data'
DROP TABLE asrs.EQUIPMENTMONITORSTATUS;

PRINT 'Deleting EQUIPMENTMONITORTAB Data'
DROP TABLE asrs.EQUIPMENTMONITORTAB;

PRINT 'Deleting EQUIPMENTMONITORSTATUSTYPE Data'
DROP TABLE asrs.EQUIPMENTMONITORSTATUSTYPE;

PRINT 'Deleting EQUIPMENTMONITORTRACKING Data'
DROP TABLE asrs.EQUIPMENTMONITORTRACKING;

go
