Insert into ASRS.WEBUSERAUTHGROUP
   (AUTH_USER_GROUP_ID, USERNAME, AUTH_GROUP)
 Values
   (1, 'Administrator', 'ROLE_USER');
Insert into ASRS.WEBUSERAUTHGROUP
   (AUTH_USER_GROUP_ID, USERNAME, AUTH_GROUP)
 Values
   (2, 'Administrator', 'ROLE_ADMIN');
Insert into ASRS.WEBUSERAUTHGROUP
   (AUTH_USER_GROUP_ID, USERNAME, AUTH_GROUP)
 Values
   (3, 'su', 'ROLE_USER');
Insert into ASRS.WEBUSERAUTHGROUP
   (AUTH_USER_GROUP_ID, USERNAME, AUTH_GROUP)
 Values
   (4, 'su', 'ROLE_ADMIN');
Insert into ASRS.WEBUSERAUTHGROUP
   (AUTH_USER_GROUP_ID, USERNAME, AUTH_GROUP)
 Values
   (5, 'su', 'ROLE_MASTER');
Insert into ASRS.WEBUSERAUTHGROUP
   (AUTH_USER_GROUP_ID, USERNAME, AUTH_GROUP)
 Values
   (6, 'SKDaifuku', 'ROLE_USER');
Insert into ASRS.WEBUSERAUTHGROUP
   (AUTH_USER_GROUP_ID, USERNAME, AUTH_GROUP)
 Values
   (7, 'SKDaifuku', 'ROLE_ADMIN');
Insert into ASRS.WEBUSERAUTHGROUP
   (AUTH_USER_GROUP_ID, USERNAME, AUTH_GROUP)
 Values
   (8, 'read', 'ROLE_READONLY');
