Insert into WRXSEQUENCER
   (SSEQUENCEIDENTIFIER, SENDDEVICENAME, ISEQUENCETYPE, ISEQUENCENUMBER, IINCREMENTFACTOR, ISTARTVALUE, IRESTARTVALUE)
 Values
   ('HostToWrx', 'parallax', 370, 0, 1, 0, 200000);
Insert into WRXSEQUENCER
   (SSEQUENCEIDENTIFIER, SENDDEVICENAME, ISEQUENCETYPE, ISEQUENCENUMBER, IINCREMENTFACTOR, ISTARTVALUE, IRESTARTVALUE)
 Values
   ('WrxToHost', 'parallax', 370, 0, 1, 0, 200000);
Insert into WRXSEQUENCER
   (SSEQUENCEIDENTIFIER, SENDDEVICENAME, ISEQUENCETYPE, ISEQUENCENUMBER, IINCREMENTFACTOR, ISTARTVALUE, IRESTARTVALUE)
 Values
   ('LoadSequence', 'LoadServer', 372, 0, 1, 1, 10000);
Insert into WRXSEQUENCER
   (SSEQUENCEIDENTIFIER, SENDDEVICENAME, ISEQUENCETYPE, ISEQUENCENUMBER, IINCREMENTFACTOR, ISTARTVALUE, IRESTARTVALUE)
 Values
   ('LoadWordIndex', 'LoadServer', 372, 0, 1, 1, 448);
Insert into WRXSEQUENCER
   (SSEQUENCEIDENTIFIER, SENDDEVICENAME, ISEQUENCETYPE, ISEQUENCENUMBER, IINCREMENTFACTOR, ISTARTVALUE, IRESTARTVALUE)
 Values
   ('HostEmulation', 'parallax', 370, 0, 1, 0, 150000);
Insert into WRXSEQUENCER
   (SSEQUENCEIDENTIFIER, SENDDEVICENAME, ISEQUENCETYPE, ISEQUENCENUMBER, IINCREMENTFACTOR, ISTARTVALUE, IRESTARTVALUE)
 Values
   ('AGVInboundSeq', 'AGVController', 371, 623, 1, 1, 9999);
Insert into WRXSEQUENCER
   (SSEQUENCEIDENTIFIER, SENDDEVICENAME, ISEQUENCETYPE, ISEQUENCENUMBER, IINCREMENTFACTOR, ISTARTVALUE, IRESTARTVALUE)
 Values
   ('AGVOutboundSeq', 'AGVController', 371, 5759, 1, 1, 9999);
Insert into WRXSEQUENCER
   (SSEQUENCEIDENTIFIER, SENDDEVICENAME, ISEQUENCETYPE, ISEQUENCENUMBER, IINCREMENTFACTOR, ISTARTVALUE, IRESTARTVALUE)
 Values
   ('HeartBeatSeq', 'AGVController', 371, 9942, 1, 1, 9999);
COMMIT;

COMMIT;
