/*==========================================================================*/
/* Add WRxJ-Web Tables to an ORACLE database 								*/
/*==========================================================================*/

PROMPT '++++++++++++++++++++++++++++++++++++++++'
PROMPT '+   Adding WEBAUTHGROUP                 +'
PROMPT '++++++++++++++++++++++++++++++++++++++++'
CREATE TABLE ASRS.WEBAUTHGROUP(
    ID          NUMBER(*,0) NOT NULL,
	NAME        NVARCHAR2(26) NOT NULL, 
	DESCRIPTION NVARCHAR2(120),
    
    CONSTRAINT PK_WEBAUTHGROUP PRIMARY KEY (ID) USING INDEX TABLESPACE WRxJIndex
) TABLESPACE WRXJDATA ;

COMMENT ON COLUMN ASRS.WEBAUTHGROUP.NAME IS 'Name of Authorization group to assign to users';
COMMENT ON COLUMN ASRS.WEBAUTHGROUP.DESCRIPTION IS 'Description of the Authorization group';
COMMENT ON TABLE ASRS.WEBAUTHGROUP  IS 'User permission group entity table, defines which groups are available';

PROMPT '++++++++++++++++++++++++++++++++++++++++'
PROMPT '+   Adding WEBNAVGROUP                 +'
PROMPT '++++++++++++++++++++++++++++++++++++++++'
CREATE TABLE asrs.WEBNAVGROUP(
	id       NUMBER        GENERATED BY DEFAULT ON NULL AS IDENTITY,
	NAME     varchar2(26)  NULL,
	ICON     varchar2(100) NULL,
	STYLE    varchar2(100) NULL,
	NAVORDER int           DEFAULT 0 NOT NULL,
	
    CONSTRAINT PK_WEBNAVGROUP_ID PRIMARY KEY (ID) USING INDEX TABLESPACE WRxJIndex,
	CONSTRAINT UK_WEBNAVGROUP_NAME UNIQUE (NAME) USING INDEX TABLESPACE WRxJIndex
) TABLESPACE WRxJData;

PROMPT '++++++++++++++++++++++++++++++++++++++++'
PROMPT '+   Adding WEBNAVOPTION                +'
PROMPT '++++++++++++++++++++++++++++++++++++++++'
CREATE TABLE asrs.WEBNAVOPTION(
	id            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
	AUTHGROUPNAME varchar2(26) NULL,
	NAVGROUPNAME  varchar2(26) NULL,
	NAME          varchar2(50) NULL,
	LINK          varchar2(200) NULL,
	DESCRIPTION   varchar2(100) NULL,
	ICON          varchar2(100) NULL,
	FAVORITE      int DEFAULT 0 NOT NULL,
	ORDERNO		  int DEFAULT 0 NOT NULL,
	
    CONSTRAINT PK_WEBNAVOPTION_ID PRIMARY KEY (ID) USING INDEX TABLESPACE WRxJIndex,
	CONSTRAINT UK_WEBNAVOPTION_NAME UNIQUE (NAME) USING INDEX TABLESPACE WRxJIndex
) TABLESPACE WRxJData;

PROMPT '++++++++++++++++++++++++++++++++++++++++'
PROMPT '+   Adding WEBUSERAUTHGROUP            +'
PROMPT '++++++++++++++++++++++++++++++++++++++++'
CREATE TABLE ASRS.WEBUSERAUTHGROUP(
    AUTH_USER_GROUP_ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    USERNAME           NVARCHAR2(26) NOT NULL,
    AUTH_GROUP         NVARCHAR2(26),
    
    CONSTRAINT PK_WEBUSERAUTHGROUP PRIMARY KEY (AUTH_USER_GROUP_ID) USING INDEX TABLESPACE WRxJIndex
) TABLESPACE WRXJDATA ;

COMMENT ON COLUMN ASRS.WEBUSERAUTHGROUP.AUTH_USER_GROUP_ID IS 'Incrementally auto-generated row ID, for use in Hibernate';
COMMENT ON COLUMN ASRS.WEBUSERAUTHGROUP.USERNAME IS 'User id (FK to EMPLOYEE table)';
COMMENT ON COLUMN ASRS.WEBUSERAUTHGROUP.AUTH_GROUP IS 'Authorization group ID (FK to WEBAUTHGROUP)';
COMMENT ON TABLE ASRS.WEBUSERAUTHGROUP  IS 'Many-to-Many relationship table to assign users to multiple auth groups. Defines what permissions a user will have.';

PROMPT '++++++++++++++++++++++++++++++++++++++++'
PROMPT '+   Adding WEBUSERPREF                 +'
PROMPT '++++++++++++++++++++++++++++++++++++++++'
CREATE TABLE ASRS.WEBUSERPREF(
    ID         NUMBER(*,0)   NOT NULL, 
    USER_ID    NVARCHAR2(26) NOT NULL, 
    PREF_KEY   NVARCHAR2(56) NOT NULL, 
    PREF_VALUE NVARCHAR2(56), 
    PREF_DESC  NVARCHAR2(56),
    
    CONSTRAINT PK_WEBUSERPREF PRIMARY KEY (ID) USING INDEX TABLESPACE WRxJIndex
) TABLESPACE WRXJDATA ;
 
COMMENT ON COLUMN ASRS.WEBUSERPREF.ID IS 'Incrementally auto-generated row ID, for use in Hibernate';
COMMENT ON COLUMN ASRS.WEBUSERPREF.USER_ID IS 'User id (FK to EMPLOYEE table)';
COMMENT ON COLUMN ASRS.WEBUSERPREF.PREF_KEY IS 'Identifies the preference to set. Global numerical values are defined in web app source interfaces';
COMMENT ON COLUMN ASRS.WEBUSERPREF.PREF_VALUE IS 'Value to set preferences value, contents vary greatly';
COMMENT ON COLUMN ASRS.WEBUSERPREF.PREF_DESC IS 'Additional information or description relevant to the user preference. Often used to define areas of the application to which the preference will apply';
COMMENT ON TABLE ASRS.WEBUSERPREF  IS 'A user configuration table with key/value pairs';
