Insert into WRXSEQUENCER
   (SSEQUENCEIDENTIFIER, SENDDEVICENAME, ISEQUENCETYPE, ISEQUENCENUMBER, IINCREMENTFACTOR, ISTARTVALUE, IRESTARTVALUE, DMODIFYTIME, SADDMETHOD, SUPDATEMETHOD)
 Values
   ('AGVInboundSeq', 'AGVController', 371, 0, 1, 
    1, 9999, NULL, NULL, NULL);
Insert into WRXSEQUENCER
   (SSEQUENCEIDENTIFIER, SENDDEVICENAME, ISEQUENCETYPE, ISEQUENCENUMBER, IINCREMENTFACTOR, ISTARTVALUE, IRESTARTVALUE, DMODIFYTIME, SADDMETHOD, SUPDATEMETHOD)
 Values
   ('AGVOutboundSeq', 'AGVController', 371, 0, 1, 
    1, 9999, NULL, NULL, NULL);
COMMIT;
